### ISSUE TITLE
[FR] Change empty input statements various

### ISSUE THREAD

**Issue by SirGoodenough** [SirGoodenough/HA_Blueprints#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Find similar:
```yaml
    - alias: Do something when the fan stop condition triggers
      if: '{{ not my_off_action in (''none'', ''null'', ''unavailable'', '''') }}'
      then: !input 'off_action'
```
and change to: 
```yaml
    - alias: Do something when the fan stop condition triggers
      if: "{{ my_off_action | default('') }}"
      then: !input 'off_action'
```
