### ISSUE TITLE
Request to add voice option to door_open_tts_cloud_say_announcer_nabu_casa_required

### ISSUE THREAD

**Issue by dannymertens** [SirGoodenough/HA_Blueprints#16]
Hi,

Love the blueprint works great, just a small? Request or I hope it is, I’m not a developer :stuck_out_tongue:

But is it possible to add the voice option, like in the play media service?
Creating a setup for my brother and my niece likes this voice for her room, but the parents don’t want to have it as the default voice for the rest of the house :wink:

![image](https://github.com/SirGoodenough/HA_Blueprints/assets/46963011/6f41da7e-4952-4d29-ad3c-9dd3e3ae55e9)

FYI: [Language support - Speech service - Azure AI services | Microsoft Learn](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts)

Thanks in advance!

Kind regards,

D

**Comment by SirGoodenough** [comment]
For clarification, this is regarding the Blueprint: 
#### door_open_tts_cloud_say_announcer_nabu_casa_required

So I'm looking at this and it appears possible.  However it interferes with gender and language settings. If you pick french and the voice you pick isn't one of the French ones, or you pick a femail voice and male is selected, it will error.  There is a very long list of voices malled to languages.
https://github.com/NabuCasa/hass-nabucasa/blob/3b9bfe5425206bf91c99d630962df34e2d56fa4e/hass_nabucasa/voice.py#L50-L800

I will look at revamping the entire thing to invoke HA's frontend somehow and have them sort it out.  That might work, so I'll keep this open.

Short term look at the blueprint code.  This blueprint is just an automation with !inputs replacing the entities and data and such with a bit of added syntax at the start.  Convert it back to an automation and do what you will with it.  You can also do this and pick a voice that works with your language for you case and have your own version of this BP.  I just don't see how I can build the needed logic into existing structure of the BP.

See the added voice: yaml 2 places...
```yaml

action:
- alias: Repeat the sequence UNTIL the door is closed
  repeat:
    sequence:
    - delay: !input 'cooldown'
    - service: tts.cloud_say
      data:
        entity_id: !input 'speaker_target'
        message: !input 'announcement_message'
        options:
          gender: !input 'speaker_gender'
          voice: ChristopherNeural
        language: !input 'speaker_language'
    until:
    - condition: state
      entity_id: !input 'door_entity'
      state: 'off'
- service: tts.cloud_say
  data:
    entity_id: !input 'speaker_target'
    message: !input 'final_message'
    options:
      gender: !input 'speaker_gender'
      voice: ChristopherNeural
    language: !input 'speaker_language'
```
