### ISSUE TITLE
[BUG]  The gender option for text-to-speech in the Home Assistant Cloud integration is deprecated 

### ISSUE THREAD

**Issue by SirGoodenough** [SirGoodenough/HA_Blueprints#37]
**Which Blueprint is This Concern About / Related To?**
[tts_All_Message_Script_Blueprint](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/tts_All_Message_Script_Blueprint.yaml)

**Describe the bug**
HA is reporting:
The gender option for text-to-speech in the Home Assistant Cloud integration is deprecated and will be removed.
Please update your automations and scripts to replace the gender option with an option for a supported voice instead.

**To Reproduce**
Shows on repair page.

**Expected behavior**
Blueprint works without deprecation warning.

**Screenshots**
N/A

**What version of the blueprint has the issue?**
TTS_say_Message-2023-12-09

**What was the version of Home Assistant Core?**
Version 	core-2024.4.2
Installation Type 	Home Assistant OS
Development 	false
Supervisor 	true
Docker 	true
User 	root
Virtual Environment 	false
Python Version 	3.12.2
Operating System Family 	Linux
Operating System Version 	6.6.20-haos
CPU Architecture 	x86_64
Timezone 	America/Chicago
Configuration Directory 	/config

**What type of installation are you running?**
See Above

**YAML snippets INCLUDING the Script or Automation that you built to call the blueprint**
```yaml
tts_tarantula_print_complete:
  alias: TTS Tarantula Print Complete
  use_blueprint:
    path: SirGoodenough/tts_All_Message_Script_Blueprint.yaml
    input:
      GTS_language: en
      TTS: tts.cloud_say
      nabu_azure_language: en-CA
      speaker_gender: male
      speaker_target: media_player.kitchen_speaker
      announcement_message: The Forge is ready for more work
  icon: mdi:spider
```

**Additional context**
