### ISSUE TITLE
Helper not capturing last cube side

### ISSUE THREAD

**Issue by phairplay** [SirGoodenough/HA_Blueprints#8]
**Describe the bug**
Helper not capturing the Last side. it's seem to skip passed it, yet I noticed the automation runs twice within a few millseconds. I'm not sure if this is normal.

**To Reproduce**
1. Go to '....'

**Expected behavior**
Helper created from the blueprint should be capturing the last side the cube was on, as per the blueprint settings

**Screenshots**
https://imgur.com/a/9vXopOd
this is taken from MQTT explore
https://imgur.com/9KPJXod
taken of the automation trace showing it skipping the last side element
https://imgur.com/a/gqrpKwH
the blank helper

**What version of the blueprint has the issue?**
2023.3.0

**What was the version of Home Assistant Core?**
core-2023.3.3

**What type of installation are you running?**
Home Assistant OS

**YAML snippets INCLUDING the Script or Automation that you built to call the blueprint**
```
- id: '1679165451196'
  alias: test
  description: ''
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/Cube_Desk
      action_doubletap_face_1:
      - service: light.toggle
        entity_id: light.desk_lamp
      action_rotate_cw_face_1:
      - service: light.turn_on
        entity_id: light.desk_lamp
        data_template:
          brightness: '{{states.light.desk_lamp.attributes.brightness + 30}}'
      action_rotate_ccw_face_1:
      - service: light.turn_on
        entity_id: light.desk_lamp
        data_template:
          brightness: '{{states.light.desk_lamp.attributes.brightness - 30}}'
      action_doubletap_face_2:
      - service: script.turn_on
        entity_id: script.lg_playroom_pc_on
      action_flipped90_face_3:
      - service: light.turn_on
        entity_id: light.games_room
      action_doubletap_face_3:
      - service: light.turn_on
        entity_id: light.games_room
        data:
            brightness: 76
      action_rotate_cw_face_3:
      - service: light.turn_on
        entity_id: light.games_room
        data_template:
          brightness: '{{states.light.games_room.attributes.brightness + 30}}'
      action_rotate_ccw_face_3:
      - service: light.turn_on
        entity_id: light.games_room
        data_template:
          brightness: '{{states.light.games_room.attributes.brightness - 30}}'
      action_flipped90_face_5:
      - service: media_player.turn_on
        data: {}
        target:
          entity_id: media_player.alexander_tv
      action_doubletap_face_5:
      - service: media_player.select_source
        entity_id: media_player.alexander_tv
        data:
          source: YouTube
```

**Additional context**
